/* sub_db.js */
// 서브 아이템 컨테이너 카테고리
const conSubTabDB = [
    {id:'all', name:'전체',},
    {id:'planner', name:'다이어리 & 플래너',},
    {id:'calendar', name:'캘린더',},
    {id:'note', name:'노트 & 메모',},
    {id:'pen', name:'펜 & 펜케이스',},
    {id:'card', name:'카드 & 엽서',},
    {id:'deco', name:'데코레이션',},
    {id:'file', name:'파일',},
    {id:'fashion', name:'패션',},
    {id:'living', name:'리빙',},
    {id:'signature', name:'시그니처',},
]

// 서브 아이템 리스트
const subItemDB = [
{
    id:1,
    title:'내 A6 노트를 보호해 줄 커버',
    size:'A6',
    img:'./images/best_item1.jpg',
    originPrice:'16,000',
    discount:'5%',
    salePrice:'15,200',
},
{
    id:2,
    title:'A6 노트 커버와 함께 사용하는 스트랩',
    size:'A6',
    img:'./images/best_item2.jpg',
    originPrice:'1,300',
    discount:'5%',
    salePrice:'1,235',
},
{
    id:3,
    title:'기록 스타일에 맞게 골라 쓰는 A6 노트 5종',
    size:'A6',
    img:'./images/best_item3.jpg',
    originPrice:'11,000',
    discount:'5%',
    salePrice:'10,450',
},
{
    id:4,
    title:'집 안 기분 좋은 포인트! 못나니즈 사각 쿠션',
    size:null,
    img:'./images/new_item1.jpg',
    originPrice:'43,000',
    discount:'15%',
    salePrice:'36,550',
},
{
    id:5,
    title:'티켓, 사진을 쏙! 나만의 작은 기억 도서관',
    size:null,
    img:'./images/new_item2.jpg',
    originPrice:'32,000',
    discount:'50%',
    salePrice:'16,000',
},
{
    id:6,
    title:'책 사이에서 잃어버린 물건을 발견한다면?',
    size:null,
    img:'./images/new_item3.jpg',
    originPrice:'9,000',
    discount:'5%',
    salePrice:'8,550',
},
{
    id:7,
    title:'생활방수 가능한 TPL 스트링 펜 케이스',
    size:null,
    img:'./images/new_item4.jpg',
    originPrice:'14,500',
    discount:'5%',
    salePrice:'13,770',
},
]